/**
 * Shin Kanzen Dokkai N3 Curated Vocabulary & Kanji Glossary
 * High-precision Indonesian definitions, readings, and reading comprehension tips
 * for all vocabulary and kanji appearing in Shin Kanzen Dokkai N3 passages.
 */

export interface DokkaiVocabEntry {
  termJp: string;
  reading: string;
  meaningId: string;
  level: "N5" | "N4" | "N3" | "N2" | "N1";
  tip?: string;
}

export const DOKKAI_VOCAB_GLOSSARY: Record<string, DokkaiVocabEntry> = {
  "かさみ": {
    termJp: "かさみ",
    reading: "かさみ",
    meaningId: "Membengkak, melonjak naik (dari kata kerja かさむ).",
    level: "N2",
    tip: "費用がかさむ = biaya terus membengkak tinggi.",
  },
  "ためら": {
    termJp: "ためら",
    reading: "ためら",
    meaningId: "Ragu-ragu, bimbang sejenak melangkah (ためらう).",
    level: "N2",
    tip: "発言をためらう = merasa ragu untuk buka suara.",
  },
  "ためらう": {
    termJp: "ためらう",
    reading: "ためらう",
    meaningId: "Ragu-ragu / bimbang untuk melangkah",
    level: "N2",
    tip: "Kosakata penting bacaan Dokkai: ためらう (ためらう).",
  },
  "ゆとり": {
    termJp: "ゆとり",
    reading: "ゆとり",
    meaningId: "Ketenangan / kelonggaran waktu dan batin",
    level: "N3",
    tip: "Kosakata penting bacaan Dokkai: ゆとり (ゆとり).",
  },
  "一律": {
    termJp: "一律",
    reading: "いちりつ",
    meaningId: "Seragam tanpa beda, pukul rata, tarif flat sama.",
    level: "N2",
    tip: "一律500円 = tarif seragam dipukul rata 500 yen.",
  },
  "一斉": {
    termJp: "一斉",
    reading: "いっせい",
    meaningId: "Serentak, bersamaan pada saat yang sama.",
    level: "N2",
    tip: "一斉に (issei ni) = serempak melakukan hal bersamaan.",
  },
  "一時利用": {
    termJp: "一時利用",
    reading: "いちじりよう",
    meaningId: "Penggunaan sementara, akses sewa harian/per jam tanpa berlangganan.",
    level: "N3",
    tip: "Opsi pemakaian fasilitas secara lepas (drop-in).",
  },
  "一時的": {
    termJp: "一時的",
    reading: "いちじてき",
    meaningId: "Bersifat sementara, temporer (tidak permanen).",
    level: "N3",
    tip: "一時的な減少 = penurunan sementara yang akan pulih kembali.",
  },
  "一気": {
    termJp: "一気",
    reading: "いっき",
    meaningId: "Sekaligus dalam satu tarikan napas, tanpa henti.",
    level: "N2",
    tip: "一気に片付ける = menyelesaikan sekaligus dalam satu waktu.",
  },
  "一覧": {
    termJp: "一覧",
    reading: "いちらん",
    meaningId: "Daftar ringkasan, tabel ikhtisar, rekapitulasi data.",
    level: "N3",
    tip: "一覧表 = tabel daftar ringkasan informasi.",
  },
  "不可欠": {
    termJp: "不可欠",
    reading: "ふかけつ",
    meaningId: "Mutlak diperlukan, esensial, tidak dapat dipisahkan.",
    level: "N2",
    tip: "〜に不可欠な要素 = unsur yang mutlak diperlukan untuk...",
  },
  "事前予約不要": {
    termJp: "事前予約不要",
    reading: "じぜんよやくふよう",
    meaningId: "Tidak memerlukan reservasi sebelumnya, langsung datang.",
    level: "N2",
    tip: "事前 (sebelumnya) + 予約 (reservasi) + 不要 (tidak perlu).",
  },
  "人": {
    termJp: "人",
    reading: "ひと / じん / にん",
    meaningId: "Orang, manusia, sosok.",
    level: "N5",
    tip: "Kanji dasar: 人 (orang), 日本人 (orang Jepang), 三人 (tiga orang).",
  },
  "人件費": {
    termJp: "人件費",
    reading: "じんけんひ",
    meaningId: "Biaya tenaga kerja, ongkos gaji karyawan.",
    level: "N2",
    tip: "Komponen biaya terbesar dalam operasional toko ritel/restoran.",
  },
  "人間関係": {
    termJp: "人間関係",
    reading: "にんげんかんけい",
    meaningId: "Hubungan antarmanusia, relasi interpersonal sosial.",
    level: "N3",
    tip: "Tema esai sosial dan psikologi yang sangat umum di JLPT N3.",
  },
  "仕舞": {
    termJp: "仕舞",
    reading: "しま",
    meaningId: "Menyimpan ke tempatnya (仕舞う - shimau).",
    level: "N3",
    tip: "しまい込む = mengurung / menyembunyikan rapat di dalam.",
  },
  "伝": {
    termJp: "伝",
    reading: "つた",
    meaningId: "Menyampaikan (伝える), meneruskan pesan/perasaan.",
    level: "N4",
    tip: "Kata kerja: 伝える (tsutaeru - transitif) / 伝わる (tsutawaru - intransitif).",
  },
  "伝える": {
    termJp: "伝える",
    reading: "つたえる",
    meaningId: "Menyampaikan pesan, mengabarkan, meneruskan.",
    level: "N4",
    tip: "Transitif: 気持ちを伝える = menyampaikan perasaan.",
  },
  "伝わる": {
    termJp: "伝わる",
    reading: "つたわる",
    meaningId: "Tersampaikan, menular, tersebar luas.",
    level: "N3",
    tip: "Intransitif: 気持ちが伝わる = perasaannya tersampaikan.",
  },
  "位置関係": {
    termJp: "位置関係",
    reading: "いちかんけい",
    meaningId: "Hubungan tata letak posisi relatif satu sama lain.",
    level: "N3",
    tip: "Posisi halaman kiri-kanan atau atas-bawah dalam bacaan.",
  },
  "何倍": {
    termJp: "何倍",
    reading: "なんばい",
    meaningId: "Berlipat-lipat kali, sekian kali lipat.",
    level: "N3",
    tip: "何倍もの価値がある = bernilai berkali-kali lipat lebih besar.",
  },
  "余計": {
    termJp: "余計",
    reading: "よけい",
    meaningId: "Tidak perlu, berlebihan, mubazir, menyita hal ekstra.",
    level: "N3",
    tip: "余計な手間 = kerepotan yang tidak semestinya terjadi.",
  },
  "作業記憶": {
    termJp: "作業記憶",
    reading: "さぎょうきおく",
    meaningId: "Memori kerja (working memory), kapasitas otak menyimpan & mengolah informasi sementara.",
    level: "N2",
    tip: "Istilah kognitif psikologi yang sering muncul dalam wacana sains/edukasi Dokkai.",
  },
  "依然": {
    termJp: "依然",
    reading: "いぜん",
    meaningId: "Tetap saja, masih seperti sediakala, belum berubah.",
    level: "N2",
    tip: "依然として人気がある = tetap saja populer seperti dahulu.",
  },
  "価値": {
    termJp: "価値",
    reading: "かち",
    meaningId: "Nilai, mutu kemanfaatan, harga intrinsik.",
    level: "N3",
    tip: "価値ある経験 = pengalaman yang bernilai tinggi.",
  },
  "修了": {
    termJp: "修了",
    reading: "しゅうりょう",
    meaningId: "Penyelesaian kurikulum kursus, kelulusan studi.",
    level: "N3",
    tip: "修了証 (shūryōshō) = sertifikat tanda tamat belajar.",
  },
  "個別再研修": {
    termJp: "個別再研修",
    reading: "こべつさいけんしゅう",
    meaningId: "Pelatihan ulang bimbingan personal secara individual.",
    level: "N2",
    tip: "Pelatihan remedial khusus bagi yang belum memenuhi syarat kelulusan.",
  },
  "個室": {
    termJp: "個室",
    reading: "こしつ",
    meaningId: "Kamar pribadi, ruang privat tertutup.",
    level: "N3",
    tip: "Kamar khusus di warnet, kafe kerja, atau rumah sakit.",
  },
  "先": {
    termJp: "先",
    reading: "さき / せん",
    meaningId: "Sebelumnya, ujung, depan, terlebih dahulu.",
    level: "N5",
    tip: "先生 (guru), 先週 (minggu lalu), 先に (lebih dulu).",
  },
  "入": {
    termJp: "入",
    reading: "はい / い / にゅう",
    meaningId: "Masuk, memasukkan, bergabung.",
    level: "N5",
    tip: "入る (masuk), 入れる (memasukkan), 入学 (masuk sekolah).",
  },
  "入荷作業": {
    termJp: "入荷作業",
    reading: "にゅうかさぎょう",
    meaningId: "Aktivitas penerimaan dan pembongkaran stok barang baru masuk.",
    level: "N2",
    tip: "Proses logistik memasukkan kiriman suplier ke dalam gudang.",
  },
  "円滑": {
    termJp: "円滑",
    reading: "えんかつ",
    meaningId: "Lancar, mulus, harmonis tanpa hambatan/gesekan.",
    level: "N1",
    tip: "円滑に進める / 円滑にする = membuat proses berjalan lancar.",
  },
  "冷": {
    termJp: "冷",
    reading: "つめ",
    meaningId: "Dingin benda/sikap (冷たい - tsumetai).",
    level: "N4",
    tip: "冷たい態度 = sikap dingin/cuek tanpa empati.",
  },
  "冷める": {
    termJp: "冷める",
    reading: "さめる",
    meaningId: "Menjadi dingin (makanan/antusiasme), mereda.",
    level: "N3",
    tip: "熱が冷める = panasnya mendingin / antusiasmenya memudar.",
  },
  "処理": {
    termJp: "処理",
    reading: "しょり",
    meaningId: "Pemrosesan, penanganan, penyelesaian tugas.",
    level: "N3",
    tip: "情報を処理する (memproses informasi) / 処理能力 (kapasitas penanganan).",
  },
  "出": {
    termJp: "出",
    reading: "で / だ / しゅつ",
    meaningId: "Keluar, mengeluarkan, muncul, hadir.",
    level: "N5",
    tip: "出る (keluar), 出す (mengeluarkan), 出発 (keberangkatan).",
  },
  "出張": {
    termJp: "出張",
    reading: "しゅっちょう",
    meaningId: "Perjalanan dinas bisnis luar kota",
    level: "N4",
    tip: "Kosakata penting bacaan Dokkai: 出張 (しゅっちょう).",
  },
  "出張日程": {
    termJp: "出張日程",
    reading: "しゅっちょうにってい",
    meaningId: "Jadwal agenda perjalanan dinas bisnis.",
    level: "N3",
    tip: "Rangkaian waktu kunjungan kerja ke luar daerah.",
  },
  "分": {
    termJp: "分",
    reading: "わ / ふん / ぶん",
    meaningId: "Menit, bagian, memahami, membagi.",
    level: "N5",
    tip: "分かる (paham), 自分で (sendiri), 十分 (cukup / 10 menit).",
  },
  "判断": {
    termJp: "判断",
    reading: "はんだん",
    meaningId: "Penilaian, pertimbangan keputusan, estimasi.",
    level: "N3",
    tip: "判断を下す (mengambil keputusan) / 正しい判断 (keputusan tepat).",
  },
  "削": {
    termJp: "削",
    reading: "けず",
    meaningId: "Memangkas, mengikis, meraut, mengurangi (削る).",
    level: "N3",
    tip: "Bentuk kata kerja: 削る (kezuru). Waktu istirahat yang dipangkas: 睡眠時間を削る.",
  },
  "削る": {
    termJp: "削る",
    reading: "けずる",
    meaningId: "Memangkas / mengurangi porsi",
    level: "N2",
    tip: "Kosakata penting bacaan Dokkai: 削る (けずる).",
  },
  "割引": {
    termJp: "割引",
    reading: "わりびき",
    meaningId: "Diskon, potongan harga pembelian.",
    level: "N4",
    tip: "学割 (gakuwari) = potongan diskon khusus pelajar.",
  },
  "割引対象外": {
    termJp: "割引対象外",
    reading: "わりびきたいしょうがい",
    meaningId: "Tidak termasuk dalam cakupan promo diskon (tidak berlaku diskon).",
    level: "N2",
    tip: "対象外 = di luar cakupan sasaran yang ditentukan.",
  },
  "助": {
    termJp: "助",
    reading: "たす",
    meaningId: "Membantu, menolong (助ける) / tertolong (助かる).",
    level: "N4",
    tip: "理解を助ける = membantu mempermudah pemahaman.",
  },
  "効率": {
    termJp: "効率",
    reading: "こうりつ",
    meaningId: "Efisiensi, rasio daya guna kerja terhadap waktu/biaya.",
    level: "N3",
    tip: "効率的 (efisien) / 効率が悪い (tidak efisien/boros waktu).",
  },
  "友": {
    termJp: "友",
    reading: "とも / ゆう",
    meaningId: "Teman, sahabat, kawan.",
    level: "N5",
    tip: "友達 (teman), 友人 (sahabat).",
  },
  "取得": {
    termJp: "取得",
    reading: "しゅとく",
    meaningId: "Perolehan, mendapatkan sertifikasi / izin.",
    level: "N3",
    tip: "資格を取得する = memperoleh sertifikasi kompetensi.",
  },
  "受講": {
    termJp: "受講",
    reading: "じゅこう",
    meaningId: "Mengikuti kursus / kelas pelatihan",
    level: "N2",
    tip: "Kosakata penting bacaan Dokkai: 受講 (じゅこう).",
  },
  "受講期間": {
    termJp: "受講期間",
    reading: "じゅこうきかん",
    meaningId: "Periode / batas waktu masa mengikuti kursus pelatihan.",
    level: "N3",
    tip: "Durasi tanggal mulai hingga selesai akses materi.",
  },
  "古": {
    termJp: "古",
    reading: "ふる / こ",
    meaningId: "Lama, usang, antik, purba.",
    level: "N5",
    tip: "古い (lama), 中古 (bekas).",
  },
  "各位": {
    termJp: "各位",
    reading: "かくい",
    meaningId: "Kepada Yth. seluruh anggota / hadirin sekalian.",
    level: "N2",
    tip: "Panggilan formal pembuka pengumuman email kantor: 社員各位.",
  },
  "同様": {
    termJp: "同様",
    reading: "どうよう",
    meaningId: "Sama seperti, serupa, identik keadaannya.",
    level: "N3",
    tip: "Aと同様にB = sama halnya dengan A, demikian pula B.",
  },
  "含": {
    termJp: "含",
    reading: "ふく",
    meaningId: "Mengandung, mencakup (含まれる - terkandung).",
    level: "N3",
    tip: "Kata kerja: 含む (fukumu - memuat) / 含まれる (fukumareru - termuat).",
  },
  "周囲": {
    termJp: "周囲",
    reading: "しゅうい",
    meaningId: "Orang-orang di sekitar, lingkungan keliling.",
    level: "N3",
    tip: "周囲の人々 = orang-orang di lingkungan sekitar kita.",
  },
  "和": {
    termJp: "和",
    reading: "やわ",
    meaningId: "Meredakan, melembutkan, mencairkan (和らげる).",
    level: "N3",
    tip: "空気を和らげる = mencairkan suasana agar lebih rileks.",
  },
  "和らぐ": {
    termJp: "和らぐ",
    reading: "やわらぐ",
    meaningId: "Mereda / menjadi rileks tenang",
    level: "N2",
    tip: "Kosakata penting bacaan Dokkai: 和らぐ (やわらぐ).",
  },
  "営業": {
    termJp: "営業",
    reading: "えいぎょう",
    meaningId: "Operasional bisnis, jam buka toko, aktivitas niaga.",
    level: "N3",
    tip: "24時間営業 = buka operasional 24 jam nonstop.",
  },
  "困": {
    termJp: "困",
    reading: "こま",
    meaningId: "Mengalami kesulitan, bingung, repot (困る).",
    level: "N4",
    tip: "困っている人 = orang yang sedang kesulitan/membutuhkan bantuan.",
  },
  "困る": {
    termJp: "困る",
    reading: "こまる",
    meaningId: "Kesulitan, bingung, repot, berada dalam masalah.",
    level: "N5",
    tip: "どうすればいいか困る = bingung harus bagaimana.",
  },
  "固定": {
    termJp: "固定",
    reading: "こてい",
    meaningId: "Fiksasi, pematrian tetap, penetapan kokoh.",
    level: "N3",
    tip: "情報を脳に固定する = mematri informasi agar melekat kokoh di otak.",
  },
  "土日祝日": {
    termJp: "土日祝日",
    reading: "どにちしゅくじつ",
    meaningId: "Sabtu, Minggu, dan hari libur nasional Jepang.",
    level: "N3",
    tip: "Singkatan kalender operasional: 土 (Sabtu), 日 (Minggu), 祝 (Hari Libur).",
  },
  "圧倒的": {
    termJp: "圧倒的",
    reading: "あっとうてき",
    meaningId: "Luar biasa dominan, mutlak telak perbedaannya.",
    level: "N2",
    tip: "圧倒的な差 = selisih keunggulan yang mutlak jauh.",
  },
  "基礎研修": {
    termJp: "基礎研修",
    reading: "きそけんしゅう",
    meaningId: "Pelatihan tingkat dasar, penataran orientasi pemula.",
    level: "N3",
    tip: "Pelatihan awal mengenai SOP dan standar perusahaan.",
  },
  "売": {
    termJp: "売",
    reading: "う / ばい",
    meaningId: "Menjual, penjualan.",
    level: "N5",
    tip: "売る (menjual), 売り場 (konter penjualan), 売上 (omzet).",
  },
  "変換": {
    termJp: "変換",
    reading: "へんかん",
    meaningId: "Konversi, pengubahan bentuk / format wujud.",
    level: "N3",
    tip: "長期記憶への変換 = konversi memori menjadi ingatan jangka panjang.",
  },
  "多": {
    termJp: "多",
    reading: "おお / た",
    meaningId: "Banyak, sering, berlimpah.",
    level: "N5",
    tip: "多い (banyak), 多様 (beragam), 多少 (sedikit banyak).",
  },
  "夜間": {
    termJp: "夜間",
    reading: "やかん",
    meaningId: "Malam hari, waktu malam (formal).",
    level: "N3",
    tip: "Lawan kata: 昼間 (hiruma - siang hari).",
  },
  "姿勢": {
    termJp: "姿勢",
    reading: "しせい",
    meaningId: "Sikap mental, pendirian, postur tubuh.",
    level: "N3",
    tip: "前向きな姿勢 = sikap positif yang berorientasi ke depan.",
  },
  "学": {
    termJp: "学",
    reading: "まな / がく",
    meaningId: "Belajar, studi, ilmu pengetahuan.",
    level: "N5",
    tip: "学校 (sekolah), 学生 (pelajar), 学習 (pembelajaran).",
  },
  "学生証": {
    termJp: "学生証",
    reading: "がくせいしょう",
    meaningId: "Kartu tanda mahasiswa / kartu pelajar siswa.",
    level: "N4",
    tip: "Identitas resmi untuk mendapatkan potongan tarif pelajar.",
  },
  "宅配便": {
    termJp: "宅配便",
    reading: "たくはいびん",
    meaningId: "Layanan kurir ekspedisi pengantaran paket kilat ke rumah.",
    level: "N3",
    tip: "Layanan kurir ekspres seperti Yamato (Kuroneko) atau Sagawa.",
  },
  "安": {
    termJp: "安",
    reading: "やす / あん",
    meaningId: "Murah, aman, tenteram, damai.",
    level: "N5",
    tip: "安い (murah), 安全 (aman), 安心 (tenang/lega).",
  },
  "完璧": {
    termJp: "完璧",
    reading: "かんぺき",
    meaningId: "Sempurna, tanpa cacat sedikit pun.",
    level: "N3",
    tip: "完璧を目指す = membidik kesempurnaan tanpa celah.",
  },
  "定着": {
    termJp: "定着",
    reading: "ていちゃく",
    meaningId: "Tertanam kuat, melekat di ingatan, mapan memasyarakat.",
    level: "N2",
    tip: "記憶が定着する = ingatan melekat kuat tidak mudah hilang.",
  },
  "実施": {
    termJp: "実施",
    reading: "じっし",
    meaningId: "Pelaksanaan, eksekusi program, implementasi.",
    level: "N3",
    tip: "アンケートを実施する = melaksanakan survei kuesioner.",
  },
  "客数": {
    termJp: "客数",
    reading: "きゃくすう",
    meaningId: "Jumlah pelanggan, jumlah tamu pengunjung.",
    level: "N3",
    tip: "客数が減少する = jumlah pelanggan mengalami penurunan.",
  },
  "室": {
    termJp: "室",
    reading: "しつ / むろ",
    meaningId: "Ruangan, kamar, bilik.",
    level: "N4",
    tip: "教室 (ruang kelas), 研究室 (laboratorium/ruang riset).",
  },
  "家": {
    termJp: "家",
    reading: "いえ / や / か / け",
    meaningId: "Rumah, keluarga, ahli/pakar.",
    level: "N5",
    tip: "家 (rumah), 家族 (keluarga), 専門家 (pakar/ahli).",
  },
  "容量": {
    termJp: "容量",
    reading: "ようりょう",
    meaningId: "Kapasitas, daya tampung, volume penyimpanan.",
    level: "N3",
    tip: "脳の容量 / メモリの容量 = daya tampung otak / memori.",
  },
  "対象": {
    termJp: "対象",
    reading: "たいしょう",
    meaningId: "Objek sasaran, kelompok target yang dituju.",
    level: "N3",
    tip: "研修の対象者 = peserta yang menjadi sasaran pelatihan.",
  },
  "少": {
    termJp: "少",
    reading: "すく / すこ / しょう",
    meaningId: "Sedikit, beberapa, muda.",
    level: "N5",
    tip: "少ない (sedikit), 少し (sedikit), 少年 (remaja).",
  },
  "屋": {
    termJp: "屋",
    reading: "や / おく",
    meaningId: "Toko, atap, ruangan, profesi pedagang.",
    level: "N4",
    tip: "部屋 (kamar), 本屋 (toko buku), 屋上 (rooftop).",
  },
  "年中無休": {
    termJp: "年中無休",
    reading: "ねんじゅうむきゅう",
    meaningId: "Buka sepanjang tahun tanpa hari libur (365 hari non-stop).",
    level: "N3",
    tip: "Standar operasional minimarket (konbini) dan layanan darurat Jepang.",
  },
  "広": {
    termJp: "広",
    reading: "ひろ",
    meaningId: "Luas, membentang (広い - hiroi / 広げる - melebarkan).",
    level: "N4",
    tip: "視野を広げる = memperluas wawasan/sudut pandang.",
  },
  "店": {
    termJp: "店",
    reading: "みせ / てん",
    meaningId: "Toko, kedai, gerai, restoran.",
    level: "N5",
    tip: "店 (toko), 店員 (pramuniaga), 喫茶店 (kafe/kedai kopi).",
  },
  "店舗": {
    termJp: "店舗",
    reading: "てんぽ",
    meaningId: "Gerai, gerai toko fisik, cabang retail.",
    level: "N2",
    tip: "店舗を運営する = mengelola operasional gerai toko.",
  },
  "座学": {
    termJp: "座学",
    reading: "ざがく",
    meaningId: "Pembelajaran teori di dalam kelas (non-praktik lapangan).",
    level: "N2",
    tip: "Lawan kata: 実技 (jitsugi - latihan praktik keterampilan langsung).",
  },
  "延期": {
    termJp: "延期",
    reading: "えんき",
    meaningId: "Penundaan jadwal ke tanggal atau waktu lain.",
    level: "N3",
    tip: "Sinonim: 見送り (penundaan), lawan kata: 決行 (tetap jalan).",
  },
  "引": {
    termJp: "引",
    reading: "ひ",
    meaningId: "Menarik (引っ越す = pindah rumah, 引く = menarik).",
    level: "N4",
    tip: "Dalam teks: 引っ越してきたばかり (baru saja pindah rumah).",
  },
  "引き受け": {
    termJp: "引き受け",
    reading: "ひきうけ",
    meaningId: "Penerimaan / pemrosesan barang titipan",
    level: "N2",
    tip: "Kosakata penting bacaan Dokkai: 引き受け (ひきうけ).",
  },
  "弱": {
    termJp: "弱",
    reading: "よわ / じゃく",
    meaningId: "Lemah, rapuh, sedikit kurang.",
    level: "N5",
    tip: "弱い (lemah), 弱点 (kelemahan).",
  },
  "強": {
    termJp: "強",
    reading: "し",
    meaningId: "Memaksa, mendesak (強いる - shiiru / 強い - tsuyoi).",
    level: "N3",
    tip: "無理強いする = memaksakan kehendak yang melampaui batas.",
  },
  "強いられる": {
    termJp: "強いられる",
    reading: "しいられる",
    meaningId: "Dipaksa / terpaksa harus menerima",
    level: "N2",
    tip: "Kosakata penting bacaan Dokkai: 強いられる (しいられる).",
  },
  "形式的": {
    termJp: "形式的",
    reading: "けいしきてき",
    meaningId: "Bersifat formalitas semata, sebatas aturan formal / basa-basi luar.",
    level: "N3",
    tip: "Biasa digunakan untuk mengkritik hal yang hanya formalitas tanpa esensi.",
  },
  "役員": {
    termJp: "役員",
    reading: "やくいん",
    meaningId: "Pejabat eksekutif, dewan direksi perusahaan.",
    level: "N2",
    tip: "Jajaran pimpinan pengambil kebijakan perseroan.",
  },
  "徹夜": {
    termJp: "徹夜",
    reading: "てつや",
    meaningId: "Begadang semalaman penuh tanpa tidur.",
    level: "N3",
    tip: "徹夜で勉強する = begadang semalaman belajar ujian.",
  },
  "心": {
    termJp: "心",
    reading: "こころ / しん",
    meaningId: "Hati, jiwa, perasaan batin, inti.",
    level: "N4",
    tip: "安心 (lega), 心配 (khawatir), 心理 (psikologi).",
  },
  "忘": {
    termJp: "忘",
    reading: "わす",
    meaningId: "Lupa, melupakan (忘れる - wasureru).",
    level: "N4",
    tip: "忘れられない = tidak dapat dilupakan / terkenang selalu.",
  },
  "念": {
    termJp: "念",
    reading: "ねん",
    meaningId: "Perasaan batin, rasa di dalam lubuk hati.",
    level: "N2",
    tip: "恐縮の念 = rasa sungkan yang mendalam.",
  },
  "思": {
    termJp: "思",
    reading: "おも / し",
    meaningId: "Berpikir, merasa, mengingat dalam hati.",
    level: "N5",
    tip: "思う (berpikir/berpendapat), 思い出 (kenangan).",
  },
  "思考": {
    termJp: "思考",
    reading: "しこう",
    meaningId: "Pemikiran, proses berpikir mendalam, daya cipta kognitif.",
    level: "N3",
    tip: "思考力を鍛える = melatih ketajaman daya pikir.",
  },
  "急遽": {
    termJp: "急遽",
    reading: "きゅうきょ",
    meaningId: "Mendadak, tergesa-gesa tanpa terduga sebelumnya.",
    level: "N1",
    tip: "急遽変更となる = mengalami perubahan secara mendadak.",
  },
  "恐": {
    termJp: "恐",
    reading: "おそ",
    meaningId: "Takut, cemas, khawatir (恐れる / 恐ろしい / 恐れ).",
    level: "N3",
    tip: "Pola kalimat N3: 〜恐れがある (ada kekhawatiran/risiko bahaya bahwa...).",
  },
  "恐れる": {
    termJp: "恐れる",
    reading: "おそれる",
    meaningId: "Takut akan, mengkhawatirkan sesuatu.",
    level: "N3",
    tip: "失敗を恐れる = takut akan kegagalan.",
  },
  "恐縮": {
    termJp: "恐縮",
    reading: "きょうしゅく",
    meaningId: "Rasa sungkan, merasa tidak enak hati karena merepotkan.",
    level: "N2",
    tip: "Pilar kesantunan bisnis Jepang (keigo): 恐縮ですが...",
  },
  "意図的": {
    termJp: "意図的",
    reading: "いとてき",
    meaningId: "Secara sengaja, berencana, diniatkan sejak awal.",
    level: "N2",
    tip: "意図的に時間を作る = sengaja meluangkan waktu secara terencana.",
  },
  "感触": {
    termJp: "感触",
    reading: "かんしょく",
    meaningId: "Sentuhan fisik, sensasi rabaan tangan, kesan raba.",
    level: "N2",
    tip: "紙の感触 = sensasi rabaan tekstur kertas di tangan.",
  },
  "感謝": {
    termJp: "感謝",
    reading: "かんしゃ",
    meaningId: "Rasa terima kasih, rasa syukur, apresiasi.",
    level: "N3",
    tip: "感謝の気持ちを伝える = menyampaikan rasa terima kasih.",
  },
  "成果": {
    termJp: "成果",
    reading: "せいか",
    meaningId: "Hasil kerja, pencapaian buah usaha.",
    level: "N3",
    tip: "成果を上げる = meraih hasil / prestasi nyata.",
  },
  "手軽": {
    termJp: "手軽",
    reading: "てがる",
    meaningId: "Praktis, mudah tanpa repot, ringan dijangkau.",
    level: "N3",
    tip: "手軽に利用できる = bisa dimanfaatkan dengan mudah dan praktis.",
  },
  "手間": {
    termJp: "手間",
    reading: "てま",
    meaningId: "Waktu dan tenaga, kerepotan yang harus dicurahkan.",
    level: "N3",
    tip: "手間がかかる = memakan banyak waktu dan tenaga.",
  },
  "批判": {
    termJp: "批判",
    reading: "ひはん",
    meaningId: "Kritik, kecaman, telaah sanggahan.",
    level: "N3",
    tip: "批判を恐れる = takut terhadap kritik orang lain.",
  },
  "把握": {
    termJp: "把握",
    reading: "はあく",
    meaningId: "Pemahaman utuh, memegang kendali inti masalah.",
    level: "N2",
    tip: "全体を把握する = memahami gambaran besar secara menyeluruh.",
  },
  "抱": {
    termJp: "抱",
    reading: "かか",
    meaningId: "Memikul beban, memendam persoalan sendiri (抱え込む).",
    level: "N3",
    tip: "一人で抱え込まない = jangan memendam masalah sendirian.",
  },
  "抱え込む": {
    termJp: "抱え込む",
    reading: "かかえこむ",
    meaningId: "Memendam / menanggung masalah sendirian",
    level: "N2",
    tip: "Kosakata penting bacaan Dokkai: 抱え込む (かかえこむ).",
  },
  "持": {
    termJp: "持",
    reading: "も",
    meaningId: "Membawa, memegang (持つ - motsu).",
    level: "N5",
    tip: "持ち運ぶ = membawa dan menjinjing bepergian.",
  },
  "挑戦": {
    termJp: "挑戦",
    reading: "ちょうせん",
    meaningId: "Tantangan, mencoba hal baru yang menuntut tekad.",
    level: "N3",
    tip: "挑戦する姿勢 = sikap mau menghadapi tantangan baru.",
  },
  "提示": {
    termJp: "提示",
    reading: "ていじ",
    meaningId: "Menunjukkan dokumen, memperlihatkan bukti identitas.",
    level: "N2",
    tip: "学生証を提示する = menunjukkan kartu pelajar di loket.",
  },
  "搬入": {
    termJp: "搬入",
    reading: "はんにゅう",
    meaningId: "Pemasukan barang, pengangkutan barang masuk gudang/toko.",
    level: "N2",
    tip: "Lawan kata: 搬出 (hanshutsu - pengeluaran barang).",
  },
  "改札口": {
    termJp: "改札口",
    reading: "かいさつぐち",
    meaningId: "Gerbang tiket stasiun, pintu pemeriksaan tiket kereta.",
    level: "N4",
    tip: "Tempat menempelkan kartu IC (Suica/Pasmo) di stasiun Jepang.",
  },
  "放置": {
    termJp: "放置",
    reading: "ほうち",
    meaningId: "Pembiaran, menelantarkan terbengkalai tanpa tindak lanjut.",
    level: "N2",
    tip: "放置自転車 (sepeda terbengkalai) / 放置する (membiarkan abai).",
  },
  "教訓": {
    termJp: "教訓",
    reading: "きょうくん",
    meaningId: "Pelajaran berharga, hikmah pengalaman berharga.",
    level: "N2",
    tip: "失敗から教訓を得る = memetik pelajaran berharga dari kegagalan.",
  },
  "新": {
    termJp: "新",
    reading: "あたら / しん",
    meaningId: "Baru, mutakhir, pembaruan.",
    level: "N5",
    tip: "新しい (baru), 新聞 (koran), 新幹線 (shinkansen).",
  },
  "日": {
    termJp: "日",
    reading: "ひ / にち",
    meaningId: "Hari, matahari, Jepang.",
    level: "N5",
    tip: "Kanji dasar: 日曜日 (Minggu), 毎日 (setiap hari), 日本 (Jepang).",
  },
  "日常会話": {
    termJp: "日常会話",
    reading: "にちじょうかいわ",
    meaningId: "Percakapan sehari-hari, obrolan rutin informal.",
    level: "N3",
    tip: "Sering menjadi konteks setting wacana percakapan dalam soal Dokkai.",
  },
  "日本人": {
    termJp: "日本人",
    reading: "にほんじん",
    meaningId: "Orang Jepang, warga negara Jepang.",
    level: "N5",
    tip: "Gabungan 日本 (Jepang) dan 人 (orang).",
  },
  "時": {
    termJp: "時",
    reading: "とき / じ",
    meaningId: "Waktu, jam, saat, momen.",
    level: "N5",
    tip: "時間 (waktu), 時計 (jam), 時々 (kadang-kadang).",
  },
  "書": {
    termJp: "書",
    reading: "か / しょ",
    meaningId: "Menulis, buku, dokumen, tulisan.",
    level: "N5",
    tip: "書く (menulis), 辞書 (kamus), 図書館 (perpustakaan).",
  },
  "書類": {
    termJp: "書類",
    reading: "しょるい",
    meaningId: "Dokumen, berkas tertulis, arsip administrasi.",
    level: "N3",
    tip: "書類を作成する (membuat dokumen) / 書類を提出する (mengumpulkan berkas).",
  },
  "最大": {
    termJp: "最大",
    reading: "さいだい",
    meaningId: "Maksimal, terbesar, batas paling tinggi.",
    level: "N3",
    tip: "最大のメリット = keunggulan / manfaat terbesar.",
  },
  "月額": {
    termJp: "月額",
    reading: "げつがく",
    meaningId: "Biaya tarif iuran per bulan, nominal bulanan.",
    level: "N3",
    tip: "月額料金 = biaya langganan bulanan.",
  },
  "本": {
    termJp: "本",
    reading: "ほん / もと",
    meaningId: "Buku, asal usul, pokok, utama.",
    level: "N5",
    tip: "Kanji dasar: 本 (buku), 本当 (sungguh-sungguh), 日本 (Jepang).",
  },
  "本来": {
    termJp: "本来",
    reading: "ほんらい",
    meaningId: "Pada asalnya, sebenarnya, secara hakiki.",
    level: "N3",
    tip: "Digunakan untuk membedakan makna dasar vs penggunaan konteks modern.",
  },
  "来": {
    termJp: "来",
    reading: "く / き / こ / らい",
    meaningId: "Datang, masa depan, berikutnya.",
    level: "N5",
    tip: "来る (datang), 来週 (minggu depan), 将来 (masa depan).",
  },
  "校": {
    termJp: "校",
    reading: "こう",
    meaningId: "Sekolah, memeriksa cetakan.",
    level: "N5",
    tip: "学校 (sekolah), 高校 (SMA), 校長 (kepala sekolah).",
  },
  "格段": {
    termJp: "格段",
    reading: "かくだん",
    meaningId: "Jauh berbeda kelasnya, melonjak drastis peningkatannya.",
    level: "N2",
    tip: "格段に上がる = meningkat jauh berkali-kali lipat.",
  },
  "案内": {
    termJp: "案内",
    reading: "あんない",
    meaningId: "Pemanduan, petunjuk jalan, informasi arahan.",
    level: "N4",
    tip: "案内する (memandu, mengantar) / 案内所 (pusat informasi).",
  },
  "検索機能": {
    termJp: "検索機能",
    reading: "けんさくきのう",
    meaningId: "Fitur pencarian data / penelusuran kata kunci.",
    level: "N3",
    tip: "Fasilitas sistem untuk mencari informasi secara cepat.",
  },
  "極": {
    termJp: "極",
    reading: "きわ",
    meaningId: "Sangat, teramat, mencapai batas ekstrem (極めて / 極める).",
    level: "N2",
    tip: "Kata keterangan tingkat tinggi: 極めて (kiwamete) = sangat / amat sangat.",
  },
  "極めて": {
    termJp: "極めて",
    reading: "きわめて",
    meaningId: "Amat sangat / luar biasa",
    level: "N2",
    tip: "Kosakata penting bacaan Dokkai: 極めて (きわめて).",
  },
  "機会損失": {
    termJp: "機会損失",
    reading: "きかいそんしつ",
    meaningId: "Kerugian akibat melewatkan peluang (opportunity loss).",
    level: "N2",
    tip: "Istilah bisnis: hilangnya laba potensial karena ragu bertindak.",
  },
  "正答率": {
    termJp: "正答率",
    reading: "せいとうりつ",
    meaningId: "Tingkat persentase ketepatan jawaban benar.",
    level: "N3",
    tip: "Sufiks 〜率 (ritsu) menandakan angka persentase/rasio.",
  },
  "気": {
    termJp: "気",
    reading: "き / け",
    meaningId: "Semangat, energi batin, udara, suasana rasa.",
    level: "N5",
    tip: "元気 (sehat), 天気 (cuaca), 気持ち (perasaan).",
  },
  "深刻": {
    termJp: "深刻",
    reading: "しんこく",
    meaningId: "Genting, serius, gawat berakibat parah.",
    level: "N3",
    tip: "深刻な問題 = persoalan genting yang mengancam.",
  },
  "深夜": {
    termJp: "深夜",
    reading: "しんや",
    meaningId: "Larut malam, tengah malam gulita.",
    level: "N3",
    tip: "深夜料金 = biaya tambahan tarif larut malam.",
  },
  "混雑": {
    termJp: "混雑",
    reading: "こんざつ",
    meaningId: "Kepadatan, kemacetan, ramai berdesakan orang/kendaraan.",
    level: "N3",
    tip: "混雑を避ける = menghindari jam padat / kerumunan ramai.",
  },
  "清掃": {
    termJp: "清掃",
    reading: "せいそう",
    meaningId: "Pembersihan, bersih-bersih lingkungan menyeluruh.",
    level: "N3",
    tip: "Kata formal untuk 掃除 (souji - bersih-bersih).",
  },
  "温": {
    termJp: "温",
    reading: "あたた",
    meaningId: "Hangat suhu/perasaan (温かい - atatakai).",
    level: "N4",
    tip: "温かい言葉 / 温かい心 = tutur kata/hati yang hangat penuh perhatian.",
  },
  "温まる": {
    termJp: "温まる",
    reading: "あたたまる",
    meaningId: "Menjadi hangat (badan/suasana/hati).",
    level: "N4",
    tip: "心が温まる = hati menjadi hangat/tersentuh.",
  },
  "無料": {
    termJp: "無料",
    reading: "むりょう",
    meaningId: "Gratis, cuma-cuma tanpa dipungut biaya apa pun.",
    level: "N4",
    tip: "Lawan kata: 有料 (yuuryou - berbayar).",
  },
  "無言": {
    termJp: "無言",
    reading: "むごん",
    meaningId: "Membisu, diam tanpa mengeluarkan kata sepatah pun.",
    level: "N2",
    tip: "無言の圧力 = tekanan hening tanpa kata.",
  },
  "片付": {
    termJp: "片付",
    reading: "かたづ",
    meaningId: "Beres, rampung, tertata rapi (片付ける / 片付く).",
    level: "N3",
    tip: "仕事が片付く = pekerjaan selesai tuntas terbereskan.",
  },
  "片付ける": {
    termJp: "片付ける",
    reading: "かたづける",
    meaningId: "Membereskan / menyelesaikan",
    level: "N3",
    tip: "Kosakata penting bacaan Dokkai: 片付ける (かたづける).",
  },
  "犯": {
    termJp: "犯",
    reading: "おか",
    meaningId: "Melakukan kesalahan / pelanggaran (犯す - okasu).",
    level: "N3",
    tip: "ミスを犯す = melakukan kekeliruan / kekhilafan.",
  },
  "生": {
    termJp: "生",
    reading: "い / なま / せい / しょう",
    meaningId: "Hidup, lahir, mentah, kehidupan.",
    level: "N5",
    tip: "生活 (kehidupan), 生徒 (murid), 生まれる (lahir).",
  },
  "生鮮食品": {
    termJp: "生鮮食品",
    reading: "せいせんしょくひん",
    meaningId: "Bahan makanan segar (daging, ikan, sayuran, buah).",
    level: "N3",
    tip: "Bahan pangan segar yang membutuhkan pendingin cepat saji.",
  },
  "申告": {
    termJp: "申告",
    reading: "しんこく",
    meaningId: "Pemberitahuan resmi, pelaporan deklarasi isi paket/pajak.",
    level: "N2",
    tip: "確定申告 (pelaporan SPT pajak) / 税関申告 (deklarasi pabean).",
  },
  "病": {
    termJp: "病",
    reading: "やまい / びょう",
    meaningId: "Penyakit, sakit, kondisi buruk.",
    level: "N4",
    tip: "病院 (rumah sakit), 病気 (sakit).",
  },
  "睡眠時間": {
    termJp: "睡眠時間",
    reading: "すいみんじかん",
    meaningId: "Durasi waktu tidur, jam istirahat malam.",
    level: "N3",
    tip: "睡眠時間を確保する = memastikan kecukupan durasi waktu tidur.",
  },
  "瞬時": {
    termJp: "瞬時",
    reading: "しゅんじ",
    meaningId: "Seketika, dalam sekejap mata, hitungan detik.",
    level: "N2",
    tip: "瞬時に見つける = menemukan dalam sekejap mata.",
  },
  "知恵": {
    termJp: "知恵",
    reading: "ちえ",
    meaningId: "Kearifan, kebijaksanaan, akal budi, kecerdikan.",
    level: "N3",
    tip: "Kearifan turun-temurun masyarakat untuk memecahkan masalah.",
  },
  "短": {
    termJp: "短",
    reading: "みじか / たん",
    meaningId: "Pendek, singkat, kelemahan.",
    level: "N5",
    tip: "短い (pendek/singkat), 短所 (kekurangan), 短時間 (waktu singkat).",
  },
  "礼儀": {
    termJp: "礼儀",
    reading: "れいぎ",
    meaningId: "Tata krama, etika sopan santun bermasyarakat.",
    level: "N3",
    tip: "礼儀正しい = berakhlak sopan dan beretika santun.",
  },
  "祝日": {
    termJp: "祝日",
    reading: "しゅくじつ",
    meaningId: "Hari libur nasional / tanggal merah",
    level: "N3",
    tip: "Kosakata penting bacaan Dokkai: 祝日 (しゅくじつ).",
  },
  "科学技術": {
    termJp: "科学技術",
    reading: "かがくぎじゅつ",
    meaningId: "Ilmu pengetahuan dan teknologi (Iptek).",
    level: "N3",
    tip: "Tema sentral artikel teknologi dan sains di JLPT N3.",
  },
  "空間的": {
    termJp: "空間的",
    reading: "くうかんてき",
    meaningId: "Secara spasial, berkaitan dengan tata ruang dimensi.",
    level: "N2",
    tip: "空間的位置関係 = hubungan posisi letak secara tata ruang.",
  },
  "箇所": {
    termJp: "箇所",
    reading: "かしょ",
    meaningId: "Bagian, titik, lokasi tertentu dalam teks/tempat.",
    level: "N2",
    tip: "問題の箇所 = bagian/titik yang menjadi letak persoalan.",
  },
  "節約": {
    termJp: "節約",
    reading: "せつやく",
    meaningId: "Penghematan, efisiensi konsumsi daya/keuangan.",
    level: "N3",
    tip: "時間を節約する = menghemat waktu luang.",
  },
  "精密機器": {
    termJp: "精密機器",
    reading: "せいみつきき",
    meaningId: "Peralatan presisi tinggi (elektronik, optik, kamera).",
    level: "N2",
    tip: "Barang sensitif guncangan yang memerlukan penanganan ekstra.",
  },
  "終日": {
    termJp: "終日",
    reading: "しゅうじつ",
    meaningId: "Sepanjang hari, seharian penuh (dari pagi hingga malam).",
    level: "N3",
    tip: "Kerap ditemukan di papan pengumuman/informasi fasilitas (終日禁煙, 終日運行).",
  },
  "組": {
    termJp: "組",
    reading: "く",
    meaningId: "Menyusun, memadukan jadwal (組み立てる / 組み込む).",
    level: "N3",
    tip: "スケジュールに組み込む = memasukkan ke dalam agenda harian.",
  },
  "組み込む": {
    termJp: "組み込む",
    reading: "くみこむ",
    meaningId: "Memasukkan ke dalam komponen/agenda",
    level: "N2",
    tip: "Kosakata penting bacaan Dokkai: 組み込む (くみこむ).",
  },
  "緊張感": {
    termJp: "緊張感",
    reading: "きんちょうかん",
    meaningId: "Rasa tegang, atmosfer ketegangan situasi.",
    level: "N2",
    tip: "緊張感を和らげる = mencairkan rasa tegang di ruangan.",
  },
  "緩衝材": {
    termJp: "緩衝材",
    reading: "かんしょうざい",
    meaningId: "Bahan peredam benturan (bubble wrap, busa pelindung).",
    level: "N2",
    tip: "Bahan pelindung isi paket dari benturan saat ekspedisi pengiriman.",
  },
  "縮": {
    termJp: "縮",
    reading: "ちぢ",
    meaningId: "Memperpendek, menyusutkan jarak (縮める - chijimeru).",
    level: "N3",
    tip: "距離を縮める = mempersempit jarak keakraban antarpegawai.",
  },
  "老人": {
    termJp: "老人",
    reading: "ろうじん",
    meaningId: "Orang lanjut usia, lansia, kakek/nenek.",
    level: "N3",
    tip: "Sinonim formal / umum: 高齢者 (koureisha).",
  },
  "考": {
    termJp: "考",
    reading: "かんが / こう",
    meaningId: "Memikirkan, menalar, pertimbangan logis.",
    level: "N5",
    tip: "考える (memikirkan), 考え (pemikiran), 思考 (daya pikir).",
  },
  "脳科学": {
    termJp: "脳科学",
    reading: "のうかがく",
    meaningId: "Ilmu saraf otak, neurosains.",
    level: "N2",
    tip: "Disiplin ilmu yang meneliti mekanisme kerja memori manusia.",
  },
  "良質": {
    termJp: "良質",
    reading: "りょうしつ",
    meaningId: "Kualitas baik, mutu unggul prima.",
    level: "N3",
    tip: "良質な睡眠 = tidur nyenyak yang bermutu baik.",
  },
  "行": {
    termJp: "行",
    reading: "い / ゆ / おこな / こう / ぎょう",
    meaningId: "Pergi, melakukan, baris, perjalanan.",
    level: "N5",
    tip: "行く (pergi), 行う (melaksanakan), 旅行 (liburan).",
  },
  "補償": {
    termJp: "補償",
    reading: "ほしょう",
    meaningId: "Kompensasi, ganti rugi kerusakan atau kehilangan barang.",
    level: "N2",
    tip: "補償限度額 = batas maksimal plafon klaim ganti rugi.",
  },
  "見": {
    termJp: "見",
    reading: "み / けん",
    meaningId: "Melihat, memandang, sudut pandang.",
    level: "N5",
    tip: "見る (melihat), 意見 (pendapat), 見学 (kunjungan studi).",
  },
  "視聴": {
    termJp: "視聴",
    reading: "しちょう",
    meaningId: "Menonton dan menyimak audio-video.",
    level: "N2",
    tip: "動画を視聴する = menonton tayangan video pembelajaran.",
  },
  "親": {
    termJp: "親",
    reading: "おや / した / しん",
    meaningId: "Orang tua, akrab, ramah, intim.",
    level: "N4",
    tip: "親 (orang tua), 親切 (ramah/baik hati), 両親 (kedua orang tua).",
  },
  "親切": {
    termJp: "親切",
    reading: "しんせつ",
    meaningId: "Ramah, baik hati, suka menolong.",
    level: "N4",
    tip: "親切にする / 親切に教えてくれた = memberi tahu dengan ramah.",
  },
  "触": {
    termJp: "触",
    reading: "ふ",
    meaningId: "Menyentuh, menjangkau, menyinggung (触れる - fureru).",
    level: "N3",
    tip: "本に触れる = menyentuh buku / bersentuhan dengan literatur.",
  },
  "言": {
    termJp: "言",
    reading: "い / こと / げん / ごん",
    meaningId: "Berkata, ucapan, perkataan, bahasa.",
    level: "N5",
    tip: "言う (berkata), 言葉 (kata/bahasa), 言語 (bahasa).",
  },
  "話": {
    termJp: "話",
    reading: "はな / わ",
    meaningId: "Berbicara, cerita, percakapan, topik.",
    level: "N5",
    tip: "話す (berbicara), 話 (cerita), 電話 (telepon).",
  },
  "読": {
    termJp: "読",
    reading: "よ / どく",
    meaningId: "Membaca, melafalkan.",
    level: "N5",
    tip: "読む (membaca), 読書 (membaca buku), 読解 (dokkai - pemahaman bacaan).",
  },
  "課題": {
    termJp: "課題",
    reading: "かだい",
    meaningId: "Tantangan, persoalan yang harus dipecahkan, tugas.",
    level: "N3",
    tip: "Kata kunci umum esai: permasalahan yang dihadapi organisasi.",
  },
  "謝罪": {
    termJp: "謝罪",
    reading: "しゃざい",
    meaningId: "Permohonan maaf resmi, pengakuan kesalahan.",
    level: "N2",
    tip: "Kata formal untuk menyatakan maaf dalam bisnis atau publik.",
  },
  "販売機会": {
    termJp: "販売機会",
    reading: "はんばいきかい",
    meaningId: "Peluang penjualan komersial.",
    level: "N2",
    tip: "販売機会を逃す (melewatkan peluang transaksi penjualan).",
  },
  "貴重品": {
    termJp: "貴重品",
    reading: "きちょうひん",
    meaningId: "Barang berharga (uang tunai, paspor, perhiasan emas).",
    level: "N3",
    tip: "Barang bernilai tinggi yang wajib dilaporkan khusus saat pengiriman.",
  },
  "買": {
    termJp: "買",
    reading: "か / ばい",
    meaningId: "Membeli, berbelanja.",
    level: "N5",
    tip: "買う (membeli), 買い物 (belanja).",
  },
  "越": {
    termJp: "越",
    reading: "こ",
    meaningId: "Melompati, melewati, berpindah (越す).",
    level: "N4",
    tip: "Gabungan: 引っ越し (hikkoshi - pindahan).",
  },
  "車": {
    termJp: "車",
    reading: "くるま / しゃ",
    meaningId: "Mobil, kendaraan beroda, roda.",
    level: "N5",
    tip: "車 (mobil), 電車 (kereta listrik), 自転車 (sepeda).",
  },
  "軍配": {
    termJp: "軍配",
    reading: "ぐんばい",
    meaningId: "Kipas wasit sumo; vonis pemenang perlombaan.",
    level: "N1",
    tip: "〜に軍配が上がる = kemenangan berpihak pada...",
  },
  "軍配が上がる": {
    termJp: "軍配が上がる",
    reading: "ぐんばいがあがる",
    meaningId: "Dinyatakan lebih unggul / menang (istilah sumo)",
    level: "N1",
    tip: "Kosakata penting bacaan Dokkai: 軍配が上がる (ぐんばいがあがる).",
  },
  "込": {
    termJp: "込",
    reading: "こ",
    meaningId: "Masuk ke dalam lubuk hati (込む - komu).",
    level: "N4",
    tip: "Sering menjadi verba pembantu gabungan: 抱え込む, 飛び込む.",
  },
  "近": {
    termJp: "近",
    reading: "ちか / きん",
    meaningId: "Dekat, masa kini, akrab.",
    level: "N5",
    tip: "近い (dekat), 近所 (lingkungan sekitar), 最近 (akhir-akhir ini).",
  },
  "迷": {
    termJp: "迷",
    reading: "まよ",
    meaningId: "Tersesat, bingung arah, ragu (迷う).",
    level: "N3",
    tip: "道に迷う (tersesat di jalan) / 判断に迷う (bingung memutuskan).",
  },
  "迷う": {
    termJp: "迷う",
    reading: "まよう",
    meaningId: "Tersesat di jalan, bingung atau ragu dalam memilih.",
    level: "N4",
    tip: "道に迷う = tersesat di jalan; 進路に迷う = bingung menentukan masa depan.",
  },
  "追": {
    termJp: "追",
    reading: "お",
    meaningId: "Dikejar, terburu-buru oleh waktu (追われる - owareru).",
    level: "N3",
    tip: "時間に追われる = diburu dan dikejar-kejar oleh waktu tenggat.",
  },
  "追われる": {
    termJp: "追われる",
    reading: "おわれる",
    meaningId: "Dikejar-kejar waktu / tugas menumpuk",
    level: "N2",
    tip: "Kosakata penting bacaan Dokkai: 追われる (おわれる).",
  },
  "逃": {
    termJp: "逃",
    reading: "のが",
    meaningId: "Melewatkan, meloloskan, kabur (逃す / 逃げる).",
    level: "N3",
    tip: "チャンスを逃す = menyia-nyiakan / melewatkan peluang emas.",
  },
  "通": {
    termJp: "通",
    reading: "とお",
    meaningId: "Melintas, melewati, melalui (通る).",
    level: "N4",
    tip: "通りかかる = kebetulan lewat melintas di lokasi.",
  },
  "通りすがり": {
    termJp: "通りすがり",
    reading: "とおりすがり",
    meaningId: "Orang yang kebetulan lewat di jalan",
    level: "N2",
    tip: "Kosakata penting bacaan Dokkai: 通りすがり (とおりすがり).",
  },
  "運": {
    termJp: "運",
    reading: "はこ",
    meaningId: "Mengangkut, membawa berpindah (運ぶ - hakobu).",
    level: "N4",
    tip: "荷物を運ぶ = mengangkut barang bawaan.",
  },
  "道": {
    termJp: "道",
    reading: "みち / どう / とう",
    meaningId: "Jalan, lintasan, ajaran filosofi, cara.",
    level: "N5",
    tip: "道 (jalan), 道具 (alat), 道路 (jalan raya).",
  },
  "遠": {
    termJp: "遠",
    reading: "とお / えん",
    meaningId: "Jauh, berjarak renggang.",
    level: "N5",
    tip: "遠い (jauh), 遠足 (karyawisata), 遠慮 (sungkan/menahan diri).",
  },
  "遠回": {
    termJp: "遠回",
    reading: "とおまわ",
    meaningId: "Memutar jalan lebih jauh, mengambil rute melingkar (遠回り).",
    level: "N3",
    tip: "Lawan kata: 近道 (chikamichi - jalan pintas).",
  },
  "遠回り": {
    termJp: "遠回り",
    reading: "とおまわり",
    meaningId: "Mengambil jalan memutar lebih jauh",
    level: "N3",
    tip: "Kosakata penting bacaan Dokkai: 遠回り (とおまわり).",
  },
  "部": {
    termJp: "部",
    reading: "ぶ / へ",
    meaningId: "Bagian, departemen, klub kegiatan, kamar.",
    level: "N4",
    tip: "部屋 (kamar), 部長 (manajer departemen), 全部 (semua).",
  },
  "都会": {
    termJp: "都会",
    reading: "とかい",
    meaningId: "Perkotaan, kota metropolitan besar.",
    level: "N4",
    tip: "Lawan kata: 田舎 (inaka - pedesaan).",
  },
  "都合": {
    termJp: "都合",
    reading: "つごう",
    meaningId: "Kondisi situasi, ketersediaan kelapangan waktu.",
    level: "N4",
    tip: "都合が良い (waktunya pas/leluasa) / 都合が悪い (berhalangan).",
  },
  "配慮": {
    termJp: "配慮",
    reading: "はいりょ",
    meaningId: "Perhatian, kepedulian, tenggang rasa terhadap orang lain.",
    level: "N2",
    tip: "Konsep kunci budaya Jepang: memikirkan kenyamanan lawan bicara.",
  },
  "長": {
    termJp: "長",
    reading: "なが / ちょう",
    meaningId: "Panjang, pemimpin, keunggulan.",
    level: "N5",
    tip: "長い (panjang), 社長 (direktur), 長所 (kelebihan).",
  },
  "長期的": {
    termJp: "長期的",
    reading: "ちょうきてき",
    meaningId: "Secara jangka panjang, berdurasi lama di masa depan.",
    level: "N3",
    tip: "長期的な視野 = perspektif jangka panjang.",
  },
  "閉": {
    termJp: "閉",
    reading: "し",
    meaningId: "Tutup, menutup (閉まる / 閉める).",
    level: "N4",
    tip: "店を閉める = menutup toko.",
  },
  "間": {
    termJp: "間",
    reading: "あいだ / ま / かん",
    meaningId: "Antara, selang, jarak, rentang waktu.",
    level: "N5",
    tip: "時間 (waktu durasi), 間に合う (tepat waktu), 人間 (manusia).",
  },
  "院": {
    termJp: "院",
    reading: "いん",
    meaningId: "Institusi, gedung lembaga, balai.",
    level: "N4",
    tip: "病院 (rumah sakit), 大学院 (sekolah pascasarjana).",
  },
  "陳列": {
    termJp: "陳列",
    reading: "ちんれつ",
    meaningId: "Pajangan, penataan display barang dagangan.",
    level: "N2",
    tip: "商品を陳列する = menata produk di rak etalase toko.",
  },
  "隙間": {
    termJp: "隙間",
    reading: "すきま",
    meaningId: "Celah senggang, waktu jeda luang di sela kesibukan.",
    level: "N3",
    tip: "隙間時間 (sukima jikan) = waktu luang di sela-sela rutinitas.",
  },
  "際": {
    termJp: "際",
    reading: "さい",
    meaningId: "Saat, ketika, momen (formal).",
    level: "N3",
    tip: "Tata bahasa N3: 〜の際(に) / 〜た際(に) = sinonim formal dari 〜とき.",
  },
  "集中": {
    termJp: "集中",
    reading: "しゅうちゅう",
    meaningId: "Konsentrasi, pemusatan fokus perhatian.",
    level: "N3",
    tip: "集中力を高める = meningkatkan daya konsentrasi.",
  },
  "電子書籍": {
    termJp: "電子書籍",
    reading: "でんししょせき",
    meaningId: "Buku elektronik, e-book digital.",
    level: "N3",
    tip: "Media buku digital yang dibaca melalui tablet / e-reader.",
  },
  "電気代": {
    termJp: "電気代",
    reading: "でんきだい",
    meaningId: "Biaya tagihan listrik.",
    level: "N4",
    tip: "Sufiks 〜代 (dai) menandakan biaya tarif barang/utilitas.",
  },
  "非効率的": {
    termJp: "非効率的",
    reading: "ひこうりつてき",
    meaningId: "Tidak efisien, pemborosan tenaga dan waktu.",
    level: "N2",
    tip: "Prefiks 非- (hi-) bermakna 'bukan' atau 'kontra'.",
  },
  "非常": {
    termJp: "非常",
    reading: "ひじょう",
    meaningId: "Sangat, amat luar biasa (非常に - hijou ni).",
    level: "N4",
    tip: "非常に重要 = luar biasa amat penting.",
  },
  "頃": {
    termJp: "頃",
    reading: "ころ",
    meaningId: "Waktu, masa, saat kira-kira.",
    level: "N4",
    tip: "子供の頃 (saat masih kecil), 〜た頃 (pada masa...).",
  },
  "食": {
    termJp: "食",
    reading: "た / しょく",
    meaningId: "Makan, makanan, santapan.",
    level: "N5",
    tip: "食べる (makan), 食事 (santapan), 朝食 (sarapan).",
  },
  "飲": {
    termJp: "飲",
    reading: "の / いん",
    meaningId: "Minum, menenggak.",
    level: "N5",
    tip: "飲む (minum), 飲料 (minuman), 飲み物 (minuman).",
  },
  "駅": {
    termJp: "駅",
    reading: "えき",
    meaningId: "Stasiun kereta/bus.",
    level: "N5",
    tip: "駅 (stasiun), 駅員 (petugas stasiun), 駅前 (depan stasiun).",
  },
  "高": {
    termJp: "高",
    reading: "たか / こう",
    meaningId: "Tinggi, mahal, tingkat tinggi.",
    level: "N5",
    tip: "高い (tinggi/mahal), 高校 (SMA), 最高 (terbaik/tertinggi).",
  },
};
