import type { DailyChallenge } from "../curriculum/types";

export const dailyChallenges: DailyChallenge[] = [
  {
    id: "dc-01",
    day: 1,
    title: "Reverse a String",
    description: "Write a function that reverses a string without using the built-in .reverse() method.",
    difficulty: "beginner",
    relatedModule: "js-02-functions",
    starterCode: "function reverseString(str) {\n  // Your code here\n}",
    solution: "function reverseString(str) {\n  let reversed = '';\n  for (let i = str.length - 1; i >= 0; i--) {\n    reversed += str[i];\n  }\n  return reversed;\n}",
    hint: "Loop from the end of the string to the beginning, building a new string.",
  },
  {
    id: "dc-02",
    day: 2,
    title: "Check for Palindrome",
    description: "Write a function that returns true if a string is a palindrome (reads the same forwards and backwards).",
    difficulty: "beginner",
    relatedModule: "js-02-functions",
    starterCode: "function isPalindrome(str) {\n  // Your code here\n}",
    solution: "function isPalindrome(str) {\n  const cleaned = str.toLowerCase().replace(/[^a-z0-9]/g, '');\n  return cleaned === cleaned.split('').reverse().join('');\n}",
    hint: "Clean the string first (lowercase, remove non-alphanumeric), then compare with its reverse.",
  },
  {
    id: "dc-03",
    day: 3,
    title: "FizzBuzz",
    description: "Print numbers 1-100. For multiples of 3, print 'Fizz'. For multiples of 5, print 'Buzz'. For both, print 'FizzBuzz'.",
    difficulty: "beginner",
    relatedModule: "js-01-variables",
    starterCode: "function fizzBuzz() {\n  // Your code here\n}",
    solution: "function fizzBuzz() {\n  for (let i = 1; i <= 100; i++) {\n    if (i % 15 === 0) console.log('FizzBuzz');\n    else if (i % 3 === 0) console.log('Fizz');\n    else if (i % 5 === 0) console.log('Buzz');\n    else console.log(i);\n  }\n}",
    hint: "Check for 15 (3*5) first, then 3, then 5. Order matters!",
  },
  {
    id: "dc-04",
    day: 4,
    title: "Find the Largest Number",
    description: "Write a function that takes an array of numbers and returns the largest one (without Math.max).",
    difficulty: "beginner",
    relatedModule: "js-03-array-methods",
    starterCode: "function findLargest(numbers) {\n  // Your code here\n}",
    solution: "function findLargest(numbers) {\n  return numbers.reduce((max, current) => current > max ? current : max, numbers[0]);\n}",
    hint: "Use reduce to compare each element with the current maximum.",
  },
  {
    id: "dc-05",
    day: 5,
    title: "Count Vowels",
    description: "Write a function that counts the number of vowels in a string.",
    difficulty: "beginner",
    relatedModule: "js-03-array-methods",
    starterCode: "function countVowels(str) {\n  // Your code here\n}",
    solution: "function countVowels(str) {\n  const matches = str.match(/[aeiou]/gi);\n  return matches ? matches.length : 0;\n}",
    hint: "Use a regex with match() to find all vowels, then check the length.",
  },
  {
    id: "dc-06",
    day: 6,
    title: "Sum of Even Numbers",
    description: "Write a function that takes an array and returns the sum of all even numbers.",
    difficulty: "beginner",
    relatedModule: "js-03-array-methods",
    starterCode: "function sumEven(numbers) {\n  // Your code here\n}",
    solution: "function sumEven(numbers) {\n  return numbers.filter(n => n % 2 === 0).reduce((sum, n) => sum + n, 0);\n}",
    hint: "Chain filter (for evens) and reduce (for sum).",
  },
  {
    id: "dc-07",
    day: 7,
    title: "Flatten an Array",
    description: "Write a function that flattens a nested array by one level. Example: [1, [2, 3], [4]] → [1, 2, 3, 4]",
    difficulty: "intermediate",
    relatedModule: "js-03-array-methods",
    starterCode: "function flatten(arr) {\n  // Your code here\n}",
    solution: "function flatten(arr) {\n  return arr.reduce((flat, current) => flat.concat(current), []);\n}",
    hint: "Use reduce with concat. Or use the spread operator with [].",
  },
  {
    id: "dc-08",
    day: 8,
    title: "Remove Duplicates",
    description: "Write a function that removes duplicate values from an array.",
    difficulty: "beginner",
    relatedModule: "js-04-objects",
    starterCode: "function removeDuplicates(arr) {\n  // Your code here\n}",
    solution: "function removeDuplicates(arr) {\n  return [...new Set(arr)];\n}",
    hint: "Use a Set — it automatically removes duplicates. Then spread it back into an array.",
  },
  {
    id: "dc-09",
    day: 9,
    title: "Capitalize First Letter",
    description: "Write a function that capitalizes the first letter of each word in a sentence.",
    difficulty: "beginner",
    relatedModule: "js-03-array-methods",
    starterCode: "function capitalize(str) {\n  // Your code here\n}",
    solution: "function capitalize(str) {\n  return str.split(' ').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');\n}",
    hint: "Split by space, map each word to capitalize the first char, join back.",
  },
  {
    id: "dc-10",
    day: 10,
    title: "Check for Anagram",
    description: "Write a function that returns true if two strings are anagrams of each other.",
    difficulty: "intermediate",
    relatedModule: "js-03-array-methods",
    starterCode: "function isAnagram(str1, str2) {\n  // Your code here\n}",
    solution: "function isAnagram(str1, str2) {\n  const normalize = str => str.toLowerCase().split('').sort().join('');\n  return normalize(str1) === normalize(str2);\n}",
    hint: "Normalize both strings (lowercase, sort characters) and compare.",
  },
  {
    id: "dc-11",
    day: 11,
    title: "Debounce a Function",
    description: "Write a debounce function that delays execution until after a pause in calls.",
    difficulty: "advanced",
    relatedModule: "js-06-async",
    starterCode: "function debounce(fn, delay) {\n  // Your code here\n}",
    solution: "function debounce(fn, delay) {\n  let timeoutId;\n  return function(...args) {\n    clearTimeout(timeoutId);\n    timeoutId = setTimeout(() => fn.apply(this, args), delay);\n  };\n}",
    hint: "Use a closure to store the timeout ID. Clear the previous timeout on each call.",
  },
  {
    id: "dc-12",
    day: 12,
    title: "Deep Clone an Object",
    description: "Write a function that creates a deep copy of an object (no shared references).",
    difficulty: "intermediate",
    relatedModule: "js-04-objects",
    starterCode: "function deepClone(obj) {\n  // Your code here\n}",
    solution: "function deepClone(obj) {\n  return JSON.parse(JSON.stringify(obj));\n}",
    hint: "The simplest approach: JSON.stringify then JSON.parse. (Note: doesn't work for functions or undefined.)",
  },
  {
    id: "dc-13",
    day: 13,
    title: "Group by Property",
    description: "Write a function that groups an array of objects by a given property.",
    difficulty: "intermediate",
    relatedModule: "js-03-array-methods",
    starterCode: "function groupBy(arr, key) {\n  // Your code here\n}",
    solution: "function groupBy(arr, key) {\n  return arr.reduce((groups, item) => {\n    const group = item[key];\n    if (!groups[group]) groups[group] = [];\n    groups[group].push(item);\n    return groups;\n  }, {});\n}",
    hint: "Use reduce to build an object where keys are the property values.",
  },
  {
    id: "dc-14",
    day: 14,
    title: "Promise Chain",
    description: "Write a function that fetches data from 3 URLs in sequence and returns all results.",
    difficulty: "intermediate",
    relatedModule: "js-06-async",
    starterCode: "async function fetchInSequence(urls) {\n  // Your code here\n}",
    solution: "async function fetchInSequence(urls) {\n  const results = [];\n  for (const url of urls) {\n    const res = await fetch(url);\n    results.push(await res.json());\n  }\n  return results;\n}",
    hint: "Use a for...of loop with await to fetch each URL in sequence.",
  },
  {
    id: "dc-15",
    day: 15,
    title: "Simple Event Emitter",
    description: "Create a simple event emitter with on, emit, and off methods.",
    difficulty: "advanced",
    relatedModule: "js-04-objects",
    starterCode: "function createEmitter() {\n  // Your code here\n}",
    solution: "function createEmitter() {\n  const events = {};\n  return {\n    on(event, callback) {\n      if (!events[event]) events[event] = [];\n      events[event].push(callback);\n    },\n    emit(event, data) {\n      if (events[event]) events[event].forEach(cb => cb(data));\n    },\n    off(event, callback) {\n      if (events[event]) events[event] = events[event].filter(cb => cb !== callback);\n    },\n  };\n}",
    hint: "Use an object to store event callbacks. on pushes, emit calls all, off filters out.",
  },
  {
    id: "dc-16",
    day: 16,
    title: "Memoize a Function",
    description: "Write a memoize function that caches results of expensive computations.",
    difficulty: "advanced",
    relatedModule: "js-02-functions",
    starterCode: "function memoize(fn) {\n  // Your code here\n}",
    solution: "function memoize(fn) {\n  const cache = {};\n  return function(...args) {\n    const key = JSON.stringify(args);\n    if (cache[key]) return cache[key];\n    const result = fn.apply(this, args);\n    cache[key] = result;\n    return result;\n  };\n}",
    hint: "Use a closure to store a cache object. Use JSON.stringify of arguments as the cache key.",
  },
  {
    id: "dc-17",
    day: 17,
    title: "Format Currency",
    description: "Write a function that formats a number as currency (e.g., 1000 → 'Rp1.000,00').",
    difficulty: "intermediate",
    relatedModule: "js-04-objects",
    starterCode: "function formatCurrency(amount) {\n  // Your code here\n}",
    solution: "function formatCurrency(amount) {\n  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR' }).format(amount);\n}",
    hint: "Use the built-in Intl.NumberFormat API with locale and currency options.",
  },
  {
    id: "dc-18",
    day: 18,
    title: "Validate Email",
    description: "Write a function that returns true if a string is a valid email address.",
    difficulty: "beginner",
    relatedModule: "js-01-variables",
    starterCode: "function isValidEmail(email) {\n  // Your code here\n}",
    solution: "function isValidEmail(email) {\n  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email);\n}",
    hint: "Use a regex. Basic email format: something@something.something",
  },
  {
    id: "dc-19",
    day: 19,
    title: "Throttle a Function",
    description: "Write a throttle function that limits execution to once per interval.",
    difficulty: "advanced",
    relatedModule: "js-06-async",
    starterCode: "function throttle(fn, limit) {\n  // Your code here\n}",
    solution: "function throttle(fn, limit) {\n  let inThrottle = false;\n  return function(...args) {\n    if (!inThrottle) {\n      fn.apply(this, args);\n      inThrottle = true;\n      setTimeout(() => inThrottle = false, limit);\n    }\n  };\n}",
    hint: "Use a boolean flag. Set it to true after calling, reset with setTimeout.",
  },
  {
    id: "dc-20",
    day: 20,
    title: "Countdown Timer",
    description: "Write a function that logs a countdown from N to 0, one number per second.",
    difficulty: "intermediate",
    relatedModule: "js-06-async",
    starterCode: "function countdown(n) {\n  // Your code here\n}",
    solution: "function countdown(n) {\n  const timer = setInterval(() => {\n    console.log(n);\n    if (n <= 0) clearInterval(timer);\n    n--;\n  }, 1000);\n}",
    hint: "Use setInterval. Clear the interval when n reaches 0.",
  },
  {
    id: "dc-21",
    day: 21,
    title: "Random Hex Color",
    description: "Write a function that generates a random hex color code (e.g., '#1a2b3c').",
    difficulty: "beginner",
    relatedModule: "js-01-variables",
    starterCode: "function randomColor() {\n  // Your code here\n}",
    solution: "function randomColor() {\n  return '#' + Math.floor(Math.random() * 16777215).toString(16).padStart(6, '0');\n}",
    hint: "Math.random gives 0-1. Multiply by 16777215 (0xFFFFFF), convert to hex, pad with zeros.",
  },
  {
    id: "dc-22",
    day: 22,
    title: "Fetch with Timeout",
    description: "Write a function that fetches with a timeout using Promise.race.",
    difficulty: "intermediate",
    relatedModule: "js-06-async",
    starterCode: "function fetchWithTimeout(url, ms) {\n  // Your code here\n}",
    solution: "function fetchWithTimeout(url, ms) {\n  return Promise.race([\n    fetch(url),\n    new Promise((_, reject) => setTimeout(() => reject(new Error('Timeout')), ms))\n  ]);\n}",
    hint: "Use Promise.race with the fetch and a timeout promise that rejects.",
  },
  {
    id: "dc-23",
    day: 23,
    title: "Curry a Function",
    description: "Write a curry function that converts add(a, b, c) to add(a)(b)(c).",
    difficulty: "advanced",
    relatedModule: "js-02-functions",
    starterCode: "function curry(fn) {\n  // Your code here\n}",
    solution: "function curry(fn) {\n  return function curried(...args) {\n    if (args.length >= fn.length) return fn(...args);\n    return (...more) => curried(...args, ...more);\n  };\n}",
    hint: "Return a function that checks if enough args are provided. If not, return a new function.",
  },
  {
    id: "dc-24",
    day: 24,
    title: "Simple Router",
    description: "Write a simple hash-based router that calls a handler based on the URL hash.",
    difficulty: "intermediate",
    relatedModule: "js-05-dom-events",
    starterCode: "function createRouter(routes) {\n  // Your code here\n}",
    solution: "function createRouter(routes) {\n  function handleRoute() {\n    const path = window.location.hash.slice(1) || '/';\n    const handler = routes[path] || routes['/404'] || (() => console.log('Not found'));\n    handler();\n  }\n  window.addEventListener('hashchange', handleRoute);\n  handleRoute();\n}",
    hint: "Listen to 'hashchange' event. Get the hash, find the matching handler.",
  },
  {
    id: "dc-25",
    day: 25,
    title: "Queue with Stacks",
    description: "Implement a queue using only two stacks (arrays with push/pop).",
    difficulty: "intermediate",
    relatedModule: "js-04-objects",
    starterCode: "function createQueue() {\n  // Your code here\n}",
    solution: "function createQueue() {\n  const stack1 = [], stack2 = [];\n  return {\n    enqueue(x) { stack1.push(x); },\n    dequeue() {\n      if (stack2.length === 0) {\n        while (stack1.length) stack2.push(stack1.pop());\n      }\n      return stack2.pop();\n    },\n  };\n}",
    hint: "Push to stack1. For dequeue, if stack2 is empty, transfer all from stack1 (reversing order), then pop from stack2.",
  },
  {
    id: "dc-26",
    day: 26,
    title: "Array Chunk",
    description: "Write a function that splits an array into chunks of a given size.",
    difficulty: "beginner",
    relatedModule: "js-03-array-methods",
    starterCode: "function chunk(arr, size) {\n  // Your code here\n}",
    solution: "function chunk(arr, size) {\n  const chunks = [];\n  for (let i = 0; i < arr.length; i += size) {\n    chunks.push(arr.slice(i, i + size));\n  }\n  return chunks;\n}",
    hint: "Loop with step = size. Use slice to extract each chunk.",
  },
  {
    id: "dc-27",
    day: 27,
    title: "Sleep Function",
    description: "Write a sleep function that pauses execution for a given number of milliseconds.",
    difficulty: "beginner",
    relatedModule: "js-06-async",
    starterCode: "function sleep(ms) {\n  // Your code here\n}",
    solution: "function sleep(ms) {\n  return new Promise(resolve => setTimeout(resolve, ms));\n}",
    hint: "Return a promise that resolves after setTimeout.",
  },
  {
    id: "dc-28",
    day: 28,
    title: "Object to Query String",
    description: "Write a function that converts an object to a URL query string.",
    difficulty: "intermediate",
    relatedModule: "js-04-objects",
    starterCode: "function toQueryString(obj) {\n  // Your code here\n}",
    solution: "function toQueryString(obj) {\n  return Object.entries(obj).map(([k, v]) => encodeURIComponent(k) + '=' + encodeURIComponent(v)).join('&');\n}",
    hint: "Use Object.entries, map to key=value pairs, join with '&'.",
  },
  {
    id: "dc-29",
    day: 29,
    title: "Simple State Manager",
    description: "Create a simple state manager with getState, setState, and subscribe methods.",
    difficulty: "advanced",
    relatedModule: "js-04-objects",
    starterCode: "function createStore(initialState) {\n  // Your code here\n}",
    solution: "function createStore(initialState) {\n  let state = initialState;\n  const listeners = [];\n  return {\n    getState: () => state,\n    setState: (updates) => {\n      state = { ...state, ...updates };\n      listeners.forEach(fn => fn(state));\n    },\n    subscribe: (fn) => { listeners.push(fn); return () => listeners.splice(listeners.indexOf(fn), 1); },\n  };\n}",
    hint: "Use a closure for state. Store listeners in an array. Call all listeners on setState. This is how Redux works!",
  },
  {
    id: "dc-30",
    day: 30,
    title: "Build a Mini Promise",
    description: "Create a simplified Promise class with then, catch, and resolve/reject.",
    difficulty: "advanced",
    relatedModule: "js-06-async",
    starterCode: "class MyPromise {\n  // Your code here\n}",
    solution: "class MyPromise {\n  constructor(executor) {\n    this.callbacks = [];\n    this.errorCallbacks = [];\n    const resolve = (val) => this.callbacks.forEach(cb => cb(val));\n    const reject = (err) => this.errorCallbacks.forEach(cb => cb(err));\n    executor(resolve, reject);\n  }\n  then(cb) { this.callbacks.push(cb); return this; }\n  catch(cb) { this.errorCallbacks.push(cb); return this; }\n}",
    hint: "Store callbacks in arrays. resolve/reject call all registered callbacks. Return this for chaining.",
  },
];
