import type { Locale } from "@/lib/i18n/types";
const copies = {
  id: {
    home:"Beranda",study:"Belajar",progress:"Progres",tools:"Alat belajar",more:"Lainnya",welcome:"Selamat datang",greeting:"Siap melanjutkan perjalanan belajarmu hari ini?",eyebrow:"SEDIKIT SETIAP HARI, SEMAKIN JAUH MELANGKAH",mission:"Misi belajar hari ini",focus:"Satu tugas. Fokus penuh.",start:"Mulai sesi fokus",resume:"Lanjutkan sesi terakhir",small:"Target kecil untuk menjaga ritme belajarmu.",saved:"Posisimu tersimpan. Lanjut tepat dari langkah terakhir.",n3:"Fokus N3 Suite",all:"N3 + FE IT",choose:"Ganti materi",review:"Review didahulukan",streak:"hari streak",rhythm:"Jaga ritme belajarmu",mastered:"Progres belajar",tracks:"Jalur belajar",trackSub:"Pilih materi, lanjutkan dengan ritmemu.",toolSub:"Dari hafalan sampai simulasi ujian.",words:"kosakata",patterns:"pola",passages:"bacaan",concepts:"konsep",target:"Target sesi",session:"Sesi fokus",exit:"Simpan & keluar",reveal:"Lihat jawaban",forgot:"Belum ingat",unsure:"Masih ragu",remember:"Sudah ingat",check:"Periksa jawaban",correct:"Jawaban tepat",incorrect:"Perlu diulang",next:"Selesaikan latihan",done:"Sesi selesai",summary:"Satu sesi kecil, satu langkah maju.",stop:"Selesai dulu",again:"Lanjut satu sesi",empty:"Semua materi tersedia sudah dipelajari",emptySub:"Kamu bisa memilih jalur lain atau kembali ke modul lengkap untuk latihan tambahan.",back:"Kembali ke beranda",loading:"Menyiapkan sesi belajarmu...",error:"Sesi belum bisa dimuat. Coba buka kembali beranda.",storage:"Browser belum bisa menyimpan progres atau posisi sesi. Data terbaru mungkin belum tersedia saat dibuka kembali.",translate:"Lihat terjemahan",examples:"Contoh penggunaan",connection:"Rumus sambungan",questions:"Latihan pemahaman",answered:"dijawab",count:"materi",queue:"untuk diulang",profile:"KAI-PASS",sync:"Sinkronisasi perangkat",search:"Cari materi",theme:"Ganti tema",roadmap:"Research & Lab Roadmap",close:"Tutup",foot:"Build. Learn. Progress.",chooseOrder:"Susun potongan kalimat dengan mengetuk sesuai urutan.",clear:"Reset urutan",full:"Buka modul lengkap",flashcard:"Flashcard",flip:"Balik kartu",tapFlip:"Ketuk kartu untuk melihat jawaban",answer:"Jawaban",wordSide:"Lihat kosakata",pronounce:"Dengarkan pengucapan",rateRecall:"Seberapa ingat kamu sebelum kartu dibalik?"
  },
  en: {
    home:"Overview",study:"Study",progress:"Progress",tools:"Study tools",more:"More",welcome:"Welcome back",greeting:"Ready to continue your learning journey today?",eyebrow:"SMALL STEPS EVERY DAY, STEADY PROGRESS",mission:"Today's learning mission",focus:"One task. Full focus.",start:"Start focus session",resume:"Resume last session",small:"Small goals to keep your learning on track.",saved:"Your place is saved. Pick up where you left off.",n3:"Focus on N3",all:"N3 + FE IT",choose:"Choose material",review:"Reviews first",streak:"day streak",rhythm:"Keep your rhythm",mastered:"Learning progress",tracks:"Study tracks",trackSub:"Choose material and learn at your own pace.",toolSub:"From flashcards to exam practice.",words:"words",patterns:"patterns",passages:"passages",concepts:"concepts",target:"Session goal",session:"Focus session",exit:"Save & exit",reveal:"Reveal answer",forgot:"Forgot",unsure:"Unsure",remember:"Remembered",check:"Check answer",correct:"Correct answer",incorrect:"Review needed",next:"Finish exercise",done:"Session complete",summary:"One small session, one step forward.",stop:"Finish for now",again:"One more session",empty:"All available material has been studied",emptySub:"Choose another track or open the full module for extra practice.",back:"Back to overview",loading:"Preparing your session...",error:"Could not load this session. Please return to the overview.",storage:"Your browser cannot save progress or session position. Recent answers may be unavailable when you return.",translate:"Show translation",examples:"Examples",connection:"Connection rule",questions:"Practice questions",answered:"answered",count:"items",queue:"to review",profile:"KAI-PASS",sync:"Device sync",search:"Search material",theme:"Toggle theme",roadmap:"Research & Lab Roadmap",close:"Close",foot:"Build. Learn. Progress.",chooseOrder:"Tap the sentence fragments in the correct order.",clear:"Reset order",full:"Open full module",flashcard:"Flashcard",flip:"Flip card",tapFlip:"Tap the card to reveal the answer",answer:"Answer",wordSide:"Show word",pronounce:"Hear pronunciation",rateRecall:"How well did you recall it before flipping?"
  },
  ja: {
    home:"ホーム",study:"学習",progress:"進捗",tools:"学習ツール",more:"その他",welcome:"おかえりなさい",greeting:"今日も少しずつ学習を続けましょう。",eyebrow:"毎日の小さな一歩が、大きな成長に",mission:"本日の学習ミッション",focus:"一つの課題に集中。",start:"集中セッションを開始",resume:"前回の続きから再開",small:"小さな目標で学習のリズムを守りましょう。",saved:"学習位置を保存しました。続きから再開できます。",n3:"N3に集中",all:"N3 + FE IT",choose:"教材を選ぶ",review:"復習を優先",streak:"日連続",rhythm:"学習のリズム",mastered:"学習の進捗",tracks:"学習コース",trackSub:"自分のペースで教材を選びましょう。",toolSub:"単語の復習から模擬試験まで。",words:"語",patterns:"文型",passages:"文章",concepts:"項目",target:"今回の目標",session:"集中セッション",exit:"保存して終了",reveal:"答えを見る",forgot:"忘れた",unsure:"曖昧",remember:"覚えている",check:"答えを確認",correct:"正解",incorrect:"復習が必要",next:"練習を完了",done:"セッション完了",summary:"小さな学習が、次の一歩につながります。",stop:"今日はここまで",again:"もう一回学習",empty:"利用できる教材はすべて学習済みです",emptySub:"別のコースを選ぶか、教材一覧から追加練習をしましょう。",back:"ホームに戻る",loading:"教材を準備しています...",error:"読み込めませんでした。ホームから再度お試しください。",storage:"進捗または学習位置を保存できません。再開時に最新の回答が表示されない場合があります。",translate:"翻訳を見る",examples:"例文",connection:"接続",questions:"理解度チェック",answered:"回答済み",count:"項目",queue:"復習する項目",profile:"KAI-PASS",sync:"端末同期",search:"教材を検索",theme:"テーマを切り替え",roadmap:"研究開発ロードマップ",close:"閉じる",foot:"Build. Learn. Progress.",chooseOrder:"文の断片を正しい順に選んでください。",clear:"順番をリセット",full:"教材一覧を開く",flashcard:"単語カード",flip:"カードを裏返す",tapFlip:"タップして答えを確認",answer:"答え",wordSide:"単語を見る",pronounce:"発音を聞く",rateRecall:"裏返す前にどのくらい思い出せましたか？"
  }
};
export function studyCopy(locale: Locale) { return copies[locale] || copies.id; }
export type StudyCopy = ReturnType<typeof studyCopy>;
export const TRACK_LABELS = {tango:"N3 Tango",bunpou:"N3 Bunpou",dokkai:"N3 Dokkai",fe:"FE IT Fundamental"};
