"use client";
import { useCallback, useEffect, useState } from "react";
import { BookOpen, Code2, FileText, Target, Flame, Play, Clock, ChevronRight, CreditCard, Link2, Layers, Monitor, Bookmark, Grid2X2 } from "lucide-react";
import { useLanguage } from "@/lib/i18n/context";
import { loadTangoProgress } from "@/lib/tango-n3-storage";
import { loadStudyProgress } from "@/lib/fe-study-storage";
import { loadBunpouProgress } from "@/components/bunpou-n3/bunpou-storage";
import { loadDokkaiProgress } from "@/components/dokkai-n3/dokkai-storage";
import { loadUnifiedActivityHistory, getTodayDateStr } from "@/lib/unified-study-storage";
import { FOCUS_LIMITS, FocusTrack, FocusSession, loadFocusSession, getExerciseReviewIds } from "@/lib/study-focus";
import { BUNPOU_ITEMS } from "@/data/bunpou-n3/grammar-items";
import { DOKKAI_PASSAGES } from "@/data/dokkai-n3/passages";
import { TANGO_TOTAL_CARDS, FE_TOTAL_CARDS } from "@/data/learn-stats";
import { openSyncModal } from "@/lib/global-modals-store";
import { FeCandidateIdCard } from "@/components/fe-study/fe-candidate-id-card";
import { StudyShell, StudyDialog } from "./study-shell";
import { studyCopy, TRACK_LABELS } from "./study-copy";

type TrackStat={count:number;total:number;review:number};
const initialStats:Record<FocusTrack,TrackStat>={tango:{count:0,total:TANGO_TOTAL_CARDS,review:0},bunpou:{count:0,total:116,review:0},dokkai:{count:0,total:13,review:0},fe:{count:0,total:FE_TOTAL_CARDS,review:0}};
const modulePaths={tango:"tango-n3",bunpou:"bunpou-n3",dokkai:"dokkai-n3",fe:"fe-study"};
const icons={tango:BookOpen,bunpou:BookOpen,dokkai:FileText,fe:Code2};
export function StudyDashboardClient(){
  const {locale}=useLanguage(),c=studyCopy(locale);
  const [stats,setStats]=useState(initialStats),[session,setSession]=useState<FocusSession|null>(null),[selected,setSelected]=useState<FocusTrack>("tango"),[all,setAll]=useState(false),[user,setUser]=useState("Kai"),[cadetId,setCadetId]=useState("KAI-PASS"),[profile,setProfile]=useState(false),[ready,setReady]=useState(false);
  const [days,setDays]=useState<{date:string;count:number}[]>([]),[streak,setStreak]=useState(0);
  const refresh=useCallback(()=>{
    const t=loadTangoProgress(),f=loadStudyProgress(),b=loadBunpouProgress(),d=loadDokkaiProgress(),today=getTodayDateStr();
    const dueTango=new Set([...t.reviewCardIds,...t.starredCardIds].filter(id=>!t.cardNextReview[id]||t.cardNextReview[id]<=today).concat(Object.entries(t.cardNextReview).filter(([,date])=>date<=today).map(([id])=>id)));
    setStats({tango:{count:t.masteredCardIds.length,total:TANGO_TOTAL_CARDS,review:dueTango.size},bunpou:{count:b.studiedPatternIds.length,total:116,review:getExerciseReviewIds(BUNPOU_ITEMS,b.answeredQuestions,b.bookmarkedPatternIds).length},dokkai:{count:d.completedPassageIds.length,total:13,review:getExerciseReviewIds(DOKKAI_PASSAGES,d.answeredQuestions,d.bookmarkedPassageIds).length},fe:{count:f.masteredCardIds.length,total:FE_TOTAL_CARDS,review:new Set([...f.reviewCardIds,...f.starredCardIds]).size}});
    setSession(loadFocusSession());
    const history=loadUnifiedActivityHistory();const recent=[];
    for(let i=6;i>=0;i--){const date=new Date();date.setDate(date.getDate()-i);const key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;recent.push({date:key,count:history[key]?.total??((t.dailyReviews?.[key]||0)+(f.dailyReviews?.[key]||0))});}setDays(recent);
    const cursor=new Date();let currentStreak=0;const activity=(key:string)=>history[key]?.total??((t.dailyReviews?.[key]||0)+(f.dailyReviews?.[key]||0));
    const dateKey=()=>`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,"0")}-${String(cursor.getDate()).padStart(2,"0")}`;
    if(!activity(dateKey()))cursor.setDate(cursor.getDate()-1);
    while(activity(dateKey())>0&&currentStreak<36500){currentStreak++;cursor.setDate(cursor.getDate()-1);}setStreak(currentStreak);
    try{setUser(localStorage.getItem("kaidevlab_candidate_name")||"Kai");setAll(localStorage.getItem("kaidevlab_study_focus_track")==="all");let id=localStorage.getItem("kaidevlab_cadet_id");if(!id){id=`KAI-PASS-${Math.floor(1000+Math.random()*9000)}`;localStorage.setItem("kaidevlab_cadet_id",id);}setCadetId(id);}catch{}
    setReady(true);
  },[]);
  useEffect(()=>{refresh();window.addEventListener("focus",refresh);window.addEventListener("storage",refresh);window.addEventListener("kaidevlab:study_activity_recorded",refresh);return()=>{window.removeEventListener("focus",refresh);window.removeEventListener("storage",refresh);window.removeEventListener("kaidevlab:study_activity_recorded",refresh);};},[refresh]);
  const chooseFocus=(mixed:boolean)=>{setAll(mixed);if(!mixed&&selected==="fe")setSelected("tango");try{localStorage.setItem("kaidevlab_study_focus_track",mixed?"all":"n3");}catch{}};
  const tracks:FocusTrack[]=all?["tango","bunpou","dokkai","fe"]:["tango","bunpou","dokkai"];
  const unfinished=session&&!session.completed;
  const primaryTrack=unfinished?session.track:selected;
  const units={tango:c.words,bunpou:c.patterns,dokkai:c.passages,fe:c.concepts};
  const mastered=Object.values(stats).reduce((sum,item)=>sum+item.count,0),total=Object.values(stats).reduce((sum,item)=>sum+item.total,0);
  const tools=[{name:"Flashcard SRS",desc:locale==="id"?"Review kosakata dengan repetisi berspasi":"Spaced vocabulary review",path:"tango-n3/?tab=flashcards",icon:Layers},{name:"Bunpou Quiz",desc:locale==="id"?"Latihan partikel & susun bintang":"Particles & sentence ordering",path:"bunpou-n3/?tab=quiz",icon:BookOpen},{name:"Dokkai Reader",desc:locale==="id"?"Bacaan dengan furigana interaktif":"Reading with furigana",path:"dokkai-n3/",icon:FileText},{name:"Kakomon CBT",desc:locale==="id"?"Simulasi ujian FE format CBT":"FE exam practice",path:"fe-study/?tab=quiz",icon:Monitor},{name:"Pseudocode Tracer",desc:locale==="id"?"Telusuri eksekusi algoritma 科目B":"Trace 科目B algorithms",path:"fe-study/?tab=tracer",icon:Code2},{name:locale==="id"?"Catatan Salah":"Review mistakes",desc:locale==="id"?"Pelajari kembali soal yang terlewat":"Revisit incorrect answers",path:"fe-study/?tab=mistakes",icon:Bookmark}];
  return <StudyShell userName={user} onProfile={()=>setProfile(true)}><main id="study-main" className="study-main"><section className="study-welcome"><div><span className="study-eyebrow">{c.eyebrow}</span><h1>{c.welcome}, <em>{user}.</em></h1><p>{c.greeting}</p></div><div className="study-welcome-meta"><span>{ready?new Intl.DateTimeFormat(locale,{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date()):"…"}</span><div className="study-inline-actions"><button className="study-icon-button" onClick={()=>setProfile(true)} aria-label={c.profile}><CreditCard size={19}/></button><button className="study-icon-button" onClick={openSyncModal} aria-label={c.sync}><Link2 size={19}/></button></div></div></section>
    <div className="study-daily-grid"><section className="study-mission study-panel"><div className="study-panel-title"><span className="study-subject-icon tango"><Target size={23}/></span><div><span className="study-eyebrow">{c.focus}</span><h2>{c.mission}</h2></div><span className="study-review-badge">{c.review}</span></div><div className="study-focus-toggle" role="group" aria-label={c.choose}><button aria-pressed={!all} onClick={()=>chooseFocus(false)}>{c.n3}</button><button aria-pressed={all} onClick={()=>chooseFocus(true)}>{c.all}</button></div>
    <div className="study-recommended"><div><span className="study-eyebrow">{unfinished?c.resume:c.target}</span><h3>{TRACK_LABELS[primaryTrack]}</h3><p>{unfinished?c.saved:c.small}</p></div><span className="study-goal-number">{unfinished?session.itemIds.length-session.cursor:FOCUS_LIMITS[primaryTrack]}<small>{units[primaryTrack]}</small></span></div>
    <a className="study-primary" aria-disabled={!ready} href={ready?`/learn/focus/?track=${primaryTrack}${unfinished?"&resume=1":""}`:undefined}><Play size={16}/>{unfinished?c.resume:c.start}</a>
    <div className="study-mission-meta"><Clock size={14}/><span>{c.target}: {unfinished?`${session.cursor} / ${session.itemIds.length} ${c.answered}`:`${FOCUS_LIMITS[primaryTrack]} ${units[primaryTrack]}`}</span>{stats[primaryTrack].review>0&&<span className="study-review-count">{stats[primaryTrack].review} {c.queue}</span>}</div>
    <div className="study-goal-list" role="group" aria-label={c.choose}>{tracks.map(track=>{const Icon=icons[track];return <button key={track} aria-pressed={selected===track} onClick={()=>setSelected(track)}><span className={`study-subject-icon ${track}`}>{track==="tango"?<span lang="ja">あ</span>:<Icon size={19}/>}</span><span><strong>{TRACK_LABELS[track]}</strong><small>{FOCUS_LIMITS[track]} {units[track]}</small></span>{selected===track&&<span className="study-selected-dot"/>}</button>;})}</div></section>
    <section className="study-consistency study-panel" id="study-progress"><div className="study-panel-title"><Flame size={20}/><h2>{c.rhythm}</h2><span className="study-eyebrow">7 DAYS</span></div><div className="study-streak"><strong>{streak}</strong><div><b>{c.streak}</b><p>{c.small}</p></div></div><div className="study-week">{days.map(day=><div key={day.date}><span className={day.count?"is-studied":""} title={`${day.count} ${c.answered}`}>{day.count?"✓":""}</span><small>{new Intl.DateTimeFormat(locale,{weekday:"short"}).format(new Date(`${day.date}T12:00:00`))}</small></div>)}</div><div className="study-rhythm-note"><Target size={21}/><p>{c.focus}<br/><strong>{c.summary}</strong></p></div><div className="study-progress-label"><span>{c.mastered}</span><strong>{mastered.toLocaleString(locale)} <small>/ {total.toLocaleString(locale)}</small></strong></div><div className="study-progress-bar" role="progressbar" aria-label={c.mastered} aria-valuemin={0} aria-valuemax={total} aria-valuenow={mastered}><span style={{width:`${Math.min(100,mastered/total*100)}%`}}/></div></section></div>
    <section id="study-tracks" className="study-section"><div className="study-section-title"><div><h2>{c.tracks}</h2><p>{c.trackSub}</p></div><a className="study-text-link" href="/tools/n3-suite/">N3 Suite <ChevronRight size={14}/></a></div><div className="study-track-grid">{(["tango","bunpou","dokkai","fe"] as FocusTrack[]).map(track=>{const Icon=icons[track],stat=stats[track];return <article className="study-track study-panel" key={track}><div className="study-track-top"><span className={`study-subject-icon ${track}`}>{track==="tango"?<span lang="ja">あ</span>:<Icon size={23}/>}</span><span className="study-mini-tag">{track==="fe"?"IPA JAPAN":"JLPT N3"}</span></div><h3><a href={`/tools/${modulePaths[track]}/`}>{TRACK_LABELS[track]}</a></h3><p>{stat.total.toLocaleString(locale)} {units[track]}</p><div className="study-progress-bar" role="progressbar" aria-label={TRACK_LABELS[track]} aria-valuemin={0} aria-valuemax={stat.total} aria-valuenow={stat.count}><span style={{width:`${Math.min(100,stat.count/stat.total*100)}%`}}/></div><div className="study-track-bottom"><span><strong>{stat.count}</strong> / {stat.total.toLocaleString(locale)}</span><a className="study-text-link" href={`/learn/focus/?track=${track}`}>{c.study}<ChevronRight size={13}/></a></div></article>;})}</div></section>
    <section id="study-tools" className="study-section"><div className="study-section-title"><div><h2>{c.tools}</h2><p>{c.toolSub}</p></div></div><div className="study-tool-grid">{tools.map(tool=><a className="study-tool" href={`/tools/${tool.path}`} key={tool.name}><tool.icon size={24}/><span><strong>{tool.name}</strong><small>{tool.desc}</small></span><ChevronRight size={16}/></a>)}</div></section>
    <details className="study-roadmap study-panel"><summary><Grid2X2 size={21}/><strong>{c.roadmap}</strong><ChevronRight size={16}/></summary><div><span>Tech English</span><span>Web Engineering</span><span>AI & Agents</span><a className="study-text-link" href="https://kaidevlab.com/">Kaidevlab Lab</a></div></details><footer className="study-footer"><span>© 2026 Kaidevlab Study · {c.foot}</span><div><button onClick={openSyncModal}>{c.sync}</button><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="https://github.com/kaidev-pro">GitHub</a></div></footer>
    </main>{profile&&<StudyDialog title={c.profile} onClose={()=>setProfile(false)}><FeCandidateIdCard candidateName={user} candidateId={cadetId} examMode="hub" score={mastered} total={total} percentage={Math.round(mastered/total*100)} isPassed={false} onNameChange={name=>{setUser(name);try{localStorage.setItem("kaidevlab_candidate_name",name);}catch{}}}/></StudyDialog>}</StudyShell>;
}
